edition = "2021"
version = "Two"
max_width = 132
attr_fn_like_width = 110
array_width = 80
chain_width = 80
fn_call_width = 100
single_line_if_else_max_width = 70
single_line_let_else_max_width = 70
struct_lit_width = 30
struct_variant_width = 60
use_field_init_shorthand = true
use_try_shorthand = true
fn_args_layout = "Compressed"
error_on_line_overflow = true
error_on_unformatted = true
